repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        exclude: '.*tests/.*|.*docs/.*'
        args: [--no-strict-optional, --ignore-missing-imports, --follow-imports=silent]
        additional_dependencies: [types-all]
  - repo: https://github.com/ambv/black
    rev: 21.6b0
    hooks:
    - id: black
      language_version: python3.7
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
  - repo: .
    rev: v2.3.3
    hooks:
    - id: export-requirements-dev
